project:
  type: website
  output-dir: docs

website:
  title: "Warwick Statistics Society R Course 2025-2026"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Welcome
        href: index.qmd

      - section: "Introduction to R"
        contents: 
          - Introduction to R/introduction to r.qmd
          - Introduction to R/data types.qmd
          - Introduction to R/data structures.qmd
          - Introduction to R/operators.qmd
          - Introduction to R/variables.qmd
          - Introduction to R/control structures.qmd
          - Introduction to R/functions.qmd
          - Introduction to R/Random numbers.qmd
          - Introduction to R/figures.qmd
      - section: Mathematics to R
        contents:
          - Mathematics to Code/Mathematics to Code intro.qmd
          - Mathematics to Code/Mathematics to Code intuit.qmd
          - Mathematics to Code/Mathematics to Code Euclidean Example.qmd
          - Mathematics to Code/Mathematics to Code MonteCarlo Example.qmd
          - Mathematics to Code/Mathematics to Code NewtonRaph Example.qmd
      - section: "Linear modelling"
        contents: 
          - Modelling/Linear modelling intro.qmd
          - Modelling/What is a linear model.qmd
          - Modelling/Continuous data.qmd
          - Modelling/Categorical data.qmd
          - Modelling/Diagnostics.qmd
          - Modelling/Check your understanding.qmd
      - section: "Exploratory data analysis"
        contents: 
          - EDA/Cars dataset.qmd
          - EDA/summary tables.qmd
      - section: "Data Visualisation"
        contents:
          - Data Visualisation/introvisualisation.qmd
          - Data Visualisation/importing data.qmd
          - Data Visualisation/baseR and ggplot.qmd
          - Data Visualisation/customising graphs.qmd
          - Data Visualisation/univariate.qmd
          - Data Visualisation/bivariate.qmd
          - Data Visualisation/timegraph.qmd
          - Data Visualisation/multivar.qmd
          - Data Visualisation/othergraphs.qmd
          - Data Visualisation/advice.qmd
      - section: "Report Writing"
        contents:
          - Report Writing/reportintro.qmd
          - Report Writing/reportstructure.qmd
          - Report Writing/reportreporting.qmd
          - Report Writing/reportenglish.qmd
          - Report Writing/reportai.qmd

  navbar:
      left:
        - href: index.qmd
          text: Home
        - href: about.qmd
          text: Using R
        - href: cheatsheets.qmd
          text: Cheatsheets
        - href: Data/Raw data.qmd
          text: Data
      tools:
         - icon: github
           href: https://github.com/Niko-Gigi/Warwick-Statistics-Society-R-Course-2025-26
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

server:
  shiny: true


